name: 'Deploy to gh-pages'
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 */12 * * *'
jobs:
  deploy-gh-pages:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Use Node.js 14.5'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '14.5'
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'Install dependencies'
        run: 'yarn install --frozen-lockfile'
      - name: 'Build'
        run: 'yarn build'
      - name: 'Deploy'
        uses: 'peaceiris/actions-gh-pages@v3'
        with:
          user_email: 'github.actions@tegebu.com'
          user_name: 'tegebu github actions'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: './_book'
          cname: 'kafer.tegebu.com'
        env:
          NODE_ENV: 'production'
